os:
  - linux
  - osx

language: python

python:
  - '2.6'
  - '2.7'
  #- '3.4' # we do not support python3 yet

before_install:
  - ./travis-deps.sh

install:
  - python setup.py develop

script:
  - nosetests
